// <auto-generated />
using System;
using Airline.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airline.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251125183359_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Airline.Domain.Entities.AircraftFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AircraftModelId")
                        .HasColumnType("int");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.ToTable("AircraftFamilys");
                });

            modelBuilder.Entity("Airline.Domain.Entities.AircraftModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CargoCapacity")
                        .HasMaxLength(2)
                        .HasColumnType("float");

                    b.Property<int>("FlightRange")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int?>("ModelFamilyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("PassengerCapacity")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelFamilyId");

                    b.ToTable("AircraftModels");
                });

            modelBuilder.Entity("Airline.Domain.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ArrivalPoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeparturePoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AircraftModelId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Airline.Domain.Entities.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PassengerId")
                        .HasColumnType("int");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1985, 3, 12),
                            FullName = "Ivanov Ivan Ivanovic",
                            PassportNumber = "4244-123456"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1990, 7, 22),
                            FullName = "Petrova Maria Sergeevna",
                            PassportNumber = "4244-234567"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1978, 11, 5),
                            FullName = "Sidorov Alexey Vladimirovich",
                            PassportNumber = "4244-345678"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(2000, 1, 30),
                            FullName = "Kuznetsova Anna Olegovna",
                            PassportNumber = "4244-456789"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(1982, 9, 14),
                            FullName = "Smirnov Dmitry Andreevich",
                            PassportNumber = "4202-567890"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(1995, 4, 18),
                            FullName = "Popova Ekaterina Nikolaevna",
                            PassportNumber = "4201-678901"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateOnly(1970, 12, 25),
                            FullName = "Volkov Sergey Pavlovich",
                            PassportNumber = "4568-789012"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateOnly(1988, 6, 9),
                            FullName = "Morozova Olga Viktorovna",
                            PassportNumber = "4857-890123"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateOnly(1992, 8, 3),
                            FullName = "Lebedev Artyom Yuryevich",
                            PassportNumber = "3618-524872"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateOnly(1997, 2, 14),
                            FullName = "Novikova Daria Igorevna",
                            PassportNumber = "8574-658974"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateOnly(1983, 5, 10),
                            FullName = "Abramov Nikolay Petrovich",
                            PassportNumber = "1111-111111"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateOnly(1991, 12, 3),
                            FullName = "Belova Vera Stepanovna",
                            PassportNumber = "2222-222222"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateOnly(1987, 8, 22),
                            FullName = "Grigoryev Maxim Igorevich",
                            PassportNumber = "3333-333333"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateOnly(1999, 3, 17),
                            FullName = "Dmitrieva Sofya Andreevna",
                            PassportNumber = "4444-444444"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateOnly(1975, 11, 30),
                            FullName = "Efimov Roman Valeryevich",
                            PassportNumber = "5555-555555"
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateOnly(1994, 7, 8),
                            FullName = "Zhukova Polina Dmitrievna",
                            PassportNumber = "6666-666666"
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateOnly(1989, 1, 15),
                            FullName = "Zaitsev Ilya Olegovich",
                            PassportNumber = "7777-777777"
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateOnly(1996, 9, 25),
                            FullName = "Ivanova Kseniya Sergeevna",
                            PassportNumber = "8888-888888"
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateOnly(1981, 4, 12),
                            FullName = "Kozlov Vladislav Yuryevich",
                            PassportNumber = "9999-999999"
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateOnly(1993, 6, 20),
                            FullName = "Larionova Alina Viktorovna",
                            PassportNumber = "0041-125874"
                        },
                        new
                        {
                            Id = 21,
                            BirthDate = new DateOnly(1986, 10, 5),
                            FullName = "Makarov Daniil Pavlovich",
                            PassportNumber = "8547-123456"
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateOnly(1998, 2, 28),
                            FullName = "Nesterova Elizaveta Mikhailovna",
                            PassportNumber = "3657-234567"
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateOnly(1992, 5, 15),
                            FullName = "Preobrazhenskaya Daria Vyacheslavovna",
                            PassportNumber = "5241-658923"
                        });
                });

            modelBuilder.Entity("Airline.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHandLuggage")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<float>("TotalBaggageWeight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Airline.Domain.Entities.AircraftModel", b =>
                {
                    b.HasOne("Airline.Domain.Entities.AircraftFamily", "ModelFamily")
                        .WithMany()
                        .HasForeignKey("ModelFamilyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ModelFamily");
                });

            modelBuilder.Entity("Airline.Domain.Entities.Flight", b =>
                {
                    b.HasOne("Airline.Domain.Entities.AircraftModel", "AircraftModel")
                        .WithMany()
                        .HasForeignKey("AircraftModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AircraftModel");
                });

            modelBuilder.Entity("Airline.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Airline.Domain.Entities.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Airline.Domain.Entities.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });
#pragma warning restore 612, 618
        }
    }
}
