<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Airline.Generator-7e562f8f-4f8a-4b95-ae30-c7ef549b6112</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Confluent.Kafka" Version="9.5.2" />
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Airline.Dtos\Airline.Dtos.csproj" />
    <ProjectReference Include="..\Airline.ServiceDefaults\Airline.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
